### ISSUE TITLE
How to export to HTML CSS & JS

### ISSUE THREAD

**Issue by Aiyush-G** [code-hike/video-tutorial-maker#3]
Hi,

Great tool, I can get it working fine locally but would like to export it statically to html css and js, how can I do this? 

Thanks

**Comment by pomber** [comment]
Hi, try running `yarn export` and let me know if it works. 
For more info see https://nextjs.org/docs/advanced-features/static-html-export

**Comment by Aiyush-G** [comment]
Ok thanks will try this today!

**Comment by Aiyush-G** [comment]
Yes, it works awesomely. I followed your instructions then went to the directory in terminal with php -S localhost:8080 to start it on a local server and it works fully.

In the project, where can I inject some css so that the code and the browser are on two separate rows, ie. when viewing on mobile I would like to achieve this.

Cheers, great project!

**Comment by Aiyush-G** [comment]
Also @pomber when I export as html and then navigate to a demo, (or one I created) and then reload the page, I get 404, its seems the URL is valid until I copy and paste it.

Ie:
http://localhost:8080 --> this shows all the pages:
```
React Example
HTML example: Stimulus in 60 seconds
Svelte in 60 seconds
Test lesson
Test 2
```

But when I click on React Example: http://localhost:8080/lessons/01.react-example is the URL. But if I reload the page I get a 404, or if I copy the url and open in a new tab I also get a 404, why is this?

**Comment by Aiyush-G** [comment]
UPDATE: Solved the above issue, I needed to append .html to the end of the URL, this is an error in the code as this probably should get appended, unfortunately I don't know how to do this.

@pomber I am still unsure how to inject custom css, in particular how would I go about displaying the browser and editor on two separate row?

**Comment by Aiyush-G** [comment]
I've successfully made it responsive, I'll submit my changes later if you would like?

**Comment by pomber** [comment]
Thanks. If you need more help to change the website visit the Next.js docs.
> I'll submit my changes later if you would like?

No need to submit the changes.
